# Generated by Django 3.0 on 2019-12-09 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ST', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='squirrel',
            old_name='Runs_form',
            new_name='Runs_from',
        ),
    ]
