# Generated by Django 3.0 on 2019-12-09 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ST', '0002_auto_20191209_2204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='squirrel',
            old_name='Longtitude',
            new_name='Longitude',
        ),
    ]
